FROM nginx:alpine
WORKDIR /usr/bin/
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./entrypoint.sh ./
COPY ./healthcheck.sh ./
#ENTRYPOINT ["/usr/bin/entrypoint.sh", ""]
#CMD ["nginx -g daemon off",""]
#ENTRYPOINT ["tail", "-f", "/dev/null"]
