#version: "3.8"
services:
  backend-nginx:
    image: nginx:alpine
    container_name: backend-nginx
    env_file:
      - ./.env
    build:
      context: ./supporting-containers/nginx-backend-proxy/
      dockerfile: Dockerfile.dev
    ports:
      - "8001:80"
    volumes:
      - ./supporting-containers/nginx-backend-proxy/nginx.conf:/etc/nginx/nginx.conf:ro,Z
    depends_on:
      - backend-fastapi
    networks:
      - repaste-net

  frontend-nginx:
    image: nginx:alpine
    container_name: frontend-nginx
    env_file:
      - ./.env
    build:
      context: ./supporting-containers/nginx-frontend-proxy/
      dockerfile: Dockerfile.dev
    ports:
      - "8002:80"
    volumes:
      - ./supporting-containers/nginx-frontend-proxy/nginx.conf:/etc/nginx/nginx.conf:ro,Z
    depends_on:
      - content-exp-vite
    networks:
      - repaste-net

  content-exp-vite:
    container_name: content-exp-vite
    expose:
      - "5173" #only exposed to other containers
    env_file:
      - ./.env
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/content-expander-frontend:/app/content-expander-frontend:rw,Z
    networks:
      - repaste-net

  backend-fastapi:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    container_name: repaste-backend
    expose:
      - "8000"  # only exposed to other containers
    env_file:
      - ./.env
    depends_on: 
      - content-exp-db 
    volumes:
      - ./backend/src:/app/src:ro,Z
    networks:
      - repaste-net

  content-exp-db:
    container_name: content-exp-db
    restart: on-failure
    image: postgres:17
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - content-expander-db-2:/var/lib/postgresql/data
    networks:
      - repaste-net

networks:
  repaste-net:
    driver: bridge

volumes:
  content-expander-db-2:


